AllCops:
  Exclude:
    - 'bin/*'
  DisplayCopNames: true
  DisplayStyleGuide: true

Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 15

Style/Documentation:
  Exclude:
    - 'spec/**/*'
